### ISSUE TITLE
Entrada de dados no sistema

### ISSUE THREAD

**Issue by jpprado** [itaipubinacional/geocab#60]
O sistema, nas camadas editáveis, deve permitir as seguintes entradas:
(1) Inserção de pares de coordenadas (Latitude, Longitude);
(2) Upload de arquivo espacial, exemplo, shapefile;
(3) Configurar camadas com geometria do tipo linha;
(4) Configurar camadas com geometria do tipo polígono;

**Comment by rodrigopfontes** [comment]
Por se tratar de um escopo novo, a solicitação fará parte da nova ordem de serviço para implementação de novas funcionalidades previstas em backlog.
